### ISSUE TITLE
Adopt CSI for OpenStack extension beginning with Kubernetes 1.19

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener-extension-provider-openstack#1]
In order to fix gardener/gardener-extensions#200 and proceed with gardener/gardener-extensions#154 we need to enable the OpenStack CSI in the OpenStack provider.

**Comment by rfranzke** [comment]
The CSI migration is beta with 1.18, though, the CSI plugins for OpenStack are not yet ready to cater with Gardener needs. We will have to contribute there before we can migrate to CSI. Hence, postponing this issue until 1.19.

**Comment by rfranzke** [comment]
I opened https://github.com/kubernetes/cloud-provider-openstack/pull/1021 to allow disabling the individual driver services so that we can run the controller service in the seed and the node service in the shoot. However, the node service is also still depending on/requiring the cloud config and the OpenStack credentials. Anyways, this is already like it is today (the kubelet needs the credentials today as well), so it's at least not getting worse with CSI. https://github.com/kubernetes/cloud-provider-openstack/issues/1020 was opened to track this.

**Comment by vlerenc** [comment]
Wow, despite CSI still. I saw @kayrus opened the ticket. Thanks!
