### ISSUE TITLE
Remove Credentials on OpenStack Nodes

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener-extension-provider-openstack#2]
**What would you like to be added**:
Currently the `cloud-controller-manager` and the `kubelet` need a credential file on the host. This can be prevented by using the out-of-tree OpenStack cloud provider together with the CSI plugin for Cinder. 

**Why is this needed**:
Prevent users who can mount the host filesystem to read infrastructure credentials from the host.

**Comment by rfranzke** [comment]
Closing in favour of #1

**Comment by rfranzke** [comment]
Turns out that with #1 it won't be possible either to remove the credentials from the cluster. Instead of being stored on the nodes they will be stored as `Secret` in the `kube-system` namespace with CSI. Though, that's still not what we want. We can't do much on our side and have to wait for the outcome of https://github.com/kubernetes/cloud-provider-openstack/issues/1020.

**Comment by vpnachev** [comment]
Should we re-open this issue to track the progress?

**Comment by rfranzke** [comment]
I guess we can't fix it as the CSI plugin still requires the credentials in the cluster.
