### ISSUE TITLE
Mirror CCM and CSI images to GCR

### ISSUE THREAD

**Issue by kon-angelo** [gardener/gardener-extension-provider-openstack#225]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority normal
/platform openstack

**What would you like to be added**:
Use the public GCR repo to mirror CSI and CCM images that are still pulled from dockerhub and may incur rate-limits

**Why is this needed**:
Circumvent DockerHub's rate-limiting.

**Comment by vpnachev** [comment]
There is https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/imagevector/imagevector.go. 
It can be controlled via https://github.com/gardener/gardener-extension-provider-openstack/blob/cd7be7eb44a24bab792defbe5a044d5bb045511e/charts/gardener-extension-provider-openstack/values.yaml#L42-L52.

So whoever wants to avoid the docker limits can overwrite the default images from https://github.com/gardener/gardener-extension-provider-openstack/blob/master/charts/images.yaml.

Is there anything else that you want to add?

**Comment by ialidzhikov** [comment]
+1, I don't see why we have to maintain the images also in GCR. There is imagevector overwrite and locally (or wherever) you can set it to whatever.

**Comment by vlerenc** [comment]
At runtime/in production the image vector should always/only pull images from our GCR.

That's to keep the failure domain small and because we are very satisfied with GCR performance and availability (other than Quay/Docker Hub that had downtimes in the past that impacted Gardener before we started mirroring images to our GCR).

**Comment by ialidzhikov** [comment]
> At runtime/in production the image vector should always/only pull images from our GCR.
> 
> That's to keep the failure domain small and because we are very satisfied with GCR performance and availability (other than Quay/Docker Hub that had downtimes in the past that impacted Gardener before we started mirroring images to our GCR).

Sure, I agree. But we should not maintain each and every image to GCR just because the imagevector logic can be broken. We had an issue in the imagevector logic and we will fix it. It is just too much effort to double maintain all of similar images and I don't like the idea at all as I shared in similar discussions in the past.

**Comment by kon-angelo** [comment]
There were a couple of CCloud cases in the recent days, where they hit the dockerhub limit when deploying shoots. It's also a situation that can plague CCloud more than other providers. 

Maybe it's not an issue directly of this repo and can be moved to an issue of the landscape, but the problem remains and the images need a more reliable source than DockerHub. The other extensions already default to gcr for their images, hence I created this issue.

**Comment by rfranzke** [comment]
I agree with the image vector argument: This should be enough to overcome the challenges you described. We don't run infrastructure to mirror each and every image that is somewhere referenced in our open-source repositories.

> The other extensions already default to gcr for their images, hence I created this issue.

The reason is that we build the CCMs for AWS, Azure, etc. ourselves with https://github.com/gardener/cloud-provider-azure, so we also push the image to our registry. With OpenStack it's different because we don't have to build it and can just consume the communities image.

I suggest closing the issue.
