### ISSUE TITLE
Openstack: application credential support

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener-extension-provider-openstack#4]
Openstack provides application credential auth method:
https://docs.openstack.org/keystone/queens/user/application_credentials.html

It would be great if Gardener can support them.

**Comment by GeertJohan** [comment]
I'm having trouble to get the provider to play nice with an openstack provider that only provides identity v3. That seems related to this issue, I think I need to use application credentials to get the terraform provider to work with v3 keystone?

**Comment by kayrus** [comment]
@GeertJohan gardener works fine with identity v3. V3 doesn't require application credentials to work. Probably there is a typo in a password or username. You can run terraform with `TF_LOG=DEBUG` and `OS_DEBUG=1` env variables to see API debug log.

**Comment by gesslein** [comment]
I have tested v1.20.0-dev-5e20dfb2c7261c00476648c1b15cefbe1d1246b2 with application credentials sucessfully on citycloud. Thanks for adding this!

For openstack environments where regions have independent keystones (like citycloud), application credentials are created and valid for only a single region. So you need to have multiple gardener secrets and always use the right one, because you will always get a different applicationCredentialID in each region. (For User/Password this is just masked by creating the same user with the same password in all regions)

**Comment by kayrus** [comment]
@gesslein application credentials are project scoped by design. If you're switching to another region, you're switching the projectID, therefore the credentials. I don't see a problem you're trying to describe.

**Comment by gesslein** [comment]
Sorry, this was just meant as a sidenote, maybe to other users. There is no problem.

At least for citycloud the domain/tenant/project name can be the same in all regions and using only one secret with username/password does work, just with application credentials this is different (as you have not control over the id).

**Comment by kayrus** [comment]
@gesslein got it. to take the control you'll need to have named application credentials and provide your username and domain, or just a userid. cc @MartinWeindel yet another case for named application credentials.
