### ISSUE TITLE
Drop floating pool name validation

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-openstack#62]
The OpenStack validator checks that the `floatingPoolName` used for shoots is one that was previously defined in the `CloudProfile` by a Gardener operator. However, some OpenStack environments don't manage the floating pools globally (at least not all of them) but sometimes also per project. Hence, such a list in the `CloudProfile` is never complete and we should allow end-users to enter an arbitrary floating pool name in their shoot spec. The list in the `CloudProfile` can still be kept and help users/the dashboard to find out default pools.

**Comment by rfranzke** [comment]
cc @timuthy

**Comment by timuthy** [comment]
This issue is also related to the [LoadBalancerClasses](https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/apis/openstack/v1alpha1/types_controlplane.go#L34) since they belong to a `FloatingPool` in the [CloudProfile](https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/apis/openstack/v1alpha1/types_cloudprofile.go#L71). Hence, it makes sense to drop this validation as well, doesn't it?

**Comment by rfranzke** [comment]
cc @afritzler

**Comment by afritzler** [comment]
We can of course disable the `FloatingPoolName` validation but this will create a situation where users provide networks which are not reachable from the Gardener network - hence you will end up with a lot of broken clusters. I guess we could try to disable the validation for `CloudProfile` and `ControlPlane`.
